In [1]:
%pip install pyarrow

Note: you may need to restart the kernel to use updated packages.

d:\GitHub\financial-assistant\.venv\Scripts\python.exe: No module named pip

In [5]:
import pandas as pd

df = pd.read_parquet("D:\\GitHub\\financial-assistant\\data\\processed\\release_v1_f481a496651d\\issues.parquet")

print(df.shape)

print(df.columns)

print(df.info())

display(df.head())

display(df.sample(5))

display(df.describe(include="all"))

print(df.isnull().sum())

print(df.duplicated().sum())

(2315162, 6)
Index(['code', 'doc_id', 'table_id', 'cell_id', 'field', 'raw_value'], dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 2315162 entries, 0 to 2315161
Data columns (total 6 columns):
 #   Column     Dtype
---  ------     -----
 0   code       str
 1   doc_id     str
 2   table_id   str
 3   cell_id    str
 4   field      str
 5   raw_value  str
dtypes: str(6)
memory usage: 626.1 MB
None

,code,doc_id,table_id,cell_id,field,raw_value
0,unit_unknown,doc_437c2d109807ec6904088cc1de1b5becc2ba0b7661...,tbl_03a43b4a63e18f35caa28b6e7de824e4c2c91ec733...,cell_1ee5ce1806d11b671b527a4884b6ba1d81ea558a9...,unit,91.048.764.635
1,unit_unknown,doc_437c2d109807ec6904088cc1de1b5becc2ba0b7661...,tbl_03a43b4a63e18f35caa28b6e7de824e4c2c91ec733...,cell_65238cca2ebb3803463aaafb99097d9d58df94693...,unit,31.335.296.127
2,unit_unknown,doc_437c2d109807ec6904088cc1de1b5becc2ba0b7661...,tbl_03a43b4a63e18f35caa28b6e7de824e4c2c91ec733...,cell_7611f736912408976cc47ab0ff814a118caa0374a...,unit,37.190.398.970
3,unit_unknown,doc_437c2d109807ec6904088cc1de1b5becc2ba0b7661...,tbl_03a43b4a63e18f35caa28b6e7de824e4c2c91ec733...,cell_76e665c9429406684cdf290422c3c3f78c94d66be...,unit,1.568.259.182
4,unit_unknown,doc_437c2d109807ec6904088cc1de1b5becc2ba0b7661...,tbl_03a43b4a63e18f35caa28b6e7de824e4c2c91ec733...,cell_81eb590c6697bb6be8a82e2d46490eeeac0e85a3c...,unit,7.302.977.672

,code,doc_id,table_id,cell_id,field,raw_value
444549,unit_unknown,doc_2ee793ce9d406ad6502712e051b5825fce92c320fd...,tbl_08127c63ddb9bc4edbc19cd5f915c50f2e43772703...,cell_657c267de0623b89603917c996fddf2254eeca52f...,unit,-
1085613,unit_unknown,doc_47f2348913b400ea5a6280ff9d93f5a5e409ed45ff...,tbl_2dfe3535e074714aca7dc1b9e82c31fbebdf5b2da7...,cell_04745e453f70be77e6656bb298e3056cd4778a1f3...,unit,2.125.782
574485,period_incomplete,doc_d7cfb7144248e8c2b8b0419a20c46fd7b924354c48...,tbl_1b34b343fe8e14686b77b7fa9baf9b5467d152f78c...,cell_58558e5383be397d35f37a049b9759d8f4e4b320d...,period,Năm tài chính kết thúcngày 31 tháng 12 năm\n20...
207600,unit_unknown,doc_db39197c5e72d9826d1758a128edfd6228fb19f58f...,tbl_45e14a7ba99d58201e62d808e30f8f489a7324d415...,cell_3c6a2c901429612ed25a6b13135b47467b75a07d3...,unit,Công ty Cổ phần Chứng khoán MHB (“MHBS”)
1958911,unit_unknown,doc_3bad7f9431b2c252f5e821453cb1960449c4c5159c...,tbl_df85a85447cce46a2071df5e560446a62d0dd58ae5...,cell_f09ad123d0f315e9e92eaf80a1bcf3a77e6d457ef...,unit,10.102.861

,code,doc_id,table_id,cell_id,field,raw_value
count,2315162,2315162,2315162,2315144,2315162,2315162
unique,7,1961,102510,2298520,5,637777
top,unit_unknown,doc_95164c3edb650c15e4d6ac7ab476952584cf89b9e2...,tbl_b4af2121eb390a58dc215caa399ce0c9eb2c5e3a91...,cell_33cf053fc001251b14d71a93b0863805c3aa191d5...,unit,-
freq,1882870,5654,1860,3,1883296,318591

code          0
doc_id        0
table_id      0
cell_id      18
field         0
raw_value     0
dtype: int64
0